"""implemented todos

Revision ID: 11be53a831c8
Revises: 9bae4fb7cd5a
Create Date: 2024-02-09 16:48:51.721937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11be53a831c8'
down_revision = '9bae4fb7cd5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('to_do', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recurrence_rhythm', sa.Integer(), nullable=False))
        batch_op.drop_column('recurrence_rythm')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('to_do', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recurrence_rythm', sa.INTEGER(), nullable=False))
        batch_op.drop_column('recurrence_rhythm')

    # ### end Alembic commands ###
