"""modified date fields

Revision ID: a6abc6e686b1
Revises: d6a1e6857fb8
Create Date: 2024-06-05 22:42:28.618650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6abc6e686b1'
down_revision = 'd6a1e6857fb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gid_gud', schema=None) as batch_op:
        batch_op.alter_column('modified_at',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('archived_at',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('deleted_at',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gid_gud', schema=None) as batch_op:
        batch_op.alter_column('deleted_at',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('archived_at',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('modified_at',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
