"""made some fields nullable

Revision ID: b7147272ff6d
Revises: a6abc6e686b1
Create Date: 2024-06-06 00:16:51.145527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7147272ff6d'
down_revision = 'a6abc6e686b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gid_gud', schema=None) as batch_op:
        batch_op.alter_column('rec_val',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('base_amount',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('times',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gid_gud', schema=None) as batch_op:
        batch_op.alter_column('times',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('amount',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('base_amount',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('rec_val',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
