"""model setup

Revision ID: cddcdea9194f
Revises: 
Create Date: 2024-06-16 08:52:30.345499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cddcdea9194f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('modified_at', sa.String(), nullable=True),
    sa.Column('archived_at', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_archived_at'), ['archived_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_last_seen'), ['last_seen'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_modified_at'), ['modified_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('modified_at', sa.String(), nullable=True),
    sa.Column('archived_at', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.String(), nullable=True),
    sa.Column('a_brief_history_of_time', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_category_archived_at'), ['archived_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_category_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_category_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_category_modified_at'), ['modified_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_category_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_category_user_id'), ['user_id'], unique=False)

    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    op.create_table('gid_gud',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('rec_val', sa.Integer(), nullable=True),
    sa.Column('rec_unit', sa.Enum('minutes', 'hours', 'days', 'weeks', 'months', 'years', name='recurrence_units'), nullable=True),
    sa.Column('rec_next', sa.String(), nullable=True),
    sa.Column('type_of_unit', sa.String(length=10), nullable=True),
    sa.Column('base_amount', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(length=10), nullable=True),
    sa.Column('times', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('modified_at', sa.String(), nullable=True),
    sa.Column('archived_at', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.String(), nullable=True),
    sa.Column('a_history_of_violence', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gid_gud', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gid_gud_archived_at'), ['archived_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_gid_gud_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gid_gud_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_gid_gud_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_gid_gud_modified_at'), ['modified_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_gid_gud_rec_next'), ['rec_next'], unique=False)
        batch_op.create_index(batch_op.f('ix_gid_gud_user_id'), ['user_id'], unique=False)

    op.create_table('completion_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gidgud_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('completed_at', sa.String(), nullable=False),
    sa.Column('type_of_unit', sa.String(length=10), nullable=True),
    sa.Column('base_amount', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(length=10), nullable=True),
    sa.Column('times', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['gidgud_id'], ['gid_gud.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('completion_table', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_completion_table_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_completion_table_completed_at'), ['completed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_completion_table_deleted_at'), ['deleted_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('completion_table', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_completion_table_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_completion_table_completed_at'))
        batch_op.drop_index(batch_op.f('ix_completion_table_category_id'))

    op.drop_table('completion_table')
    with op.batch_alter_table('gid_gud', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gid_gud_user_id'))
        batch_op.drop_index(batch_op.f('ix_gid_gud_rec_next'))
        batch_op.drop_index(batch_op.f('ix_gid_gud_modified_at'))
        batch_op.drop_index(batch_op.f('ix_gid_gud_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_gid_gud_created_at'))
        batch_op.drop_index(batch_op.f('ix_gid_gud_category_id'))
        batch_op.drop_index(batch_op.f('ix_gid_gud_archived_at'))

    op.drop_table('gid_gud')
    op.drop_table('followers')
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_user_id'))
        batch_op.drop_index(batch_op.f('ix_category_parent_id'))
        batch_op.drop_index(batch_op.f('ix_category_modified_at'))
        batch_op.drop_index(batch_op.f('ix_category_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_category_created_at'))
        batch_op.drop_index(batch_op.f('ix_category_archived_at'))

    op.drop_table('category')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_modified_at'))
        batch_op.drop_index(batch_op.f('ix_user_last_seen'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_index(batch_op.f('ix_user_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_user_created_at'))
        batch_op.drop_index(batch_op.f('ix_user_archived_at'))

    op.drop_table('user')
    # ### end Alembic commands ###
