"""added categories and default value for categories

Revision ID: d601fdd38957
Revises: a50abe1ae959
Create Date: 2024-03-06 21:46:22.290403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd601fdd38957'
down_revision = 'a50abe1ae959'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gid', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('sub_category', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('sub_sub_category', sa.String(length=40), nullable=True))

    with op.batch_alter_table('gud', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('sub_category', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('sub_sub_category', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gud', schema=None) as batch_op:
        batch_op.drop_column('sub_sub_category')
        batch_op.drop_column('sub_category')
        batch_op.drop_column('category')

    with op.batch_alter_table('gid', schema=None) as batch_op:
        batch_op.drop_column('sub_sub_category')
        batch_op.drop_column('sub_category')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
